/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_okay_reader_plugin_utils_JNICall */

#ifndef _Included_com_okay_reader_plugin_utils_JNICall
#define _Included_com_okay_reader_plugin_utils_JNICall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_okay_reader_plugin_utils_JNICall
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_okay_reader_plugin_utils_JNICall_encrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
